### ISSUE TITLE
mpi+openmp

### ISSUE THREAD

**Issue by cxx1995** [UoB-HPC/neutral#1]
I tried to run neutral with mpirun command and I want it run in parallel with 4 mpi  process(bind to numa node) and each mpi process with 16 openmp threads. But I found that actually only the first numa node could run in parallel with 16 openmp threads, as for the other 3 numa nodes the app only runs on 1 core. Could you please tell me have you ever met such problem? Thanks a lot.

**Comment by mattmartineau** [comment]
Hi, apologies for the slow reply but I didn't spot any notification for this issue and just stumbled across it. You have probably already seen but the master branch does not currently have MPI. Some versions of the code have had MPI in but they have stagnated unfortunately. There is a chance that I will revisit the functionality in the future but for the time being the code is primarily focused on single node performance. Let me know if you have any other questions.

**Comment by cxx1995** [comment]
Thanks a lot for your reply, because of the processor's weakness lead to low bandwidth between dual sockets, we chose mpi+omp as the way of running neutral on single node. Still thanks for your help :)
